### ISSUE TITLE
Please provide an example of a weekly command for an Apache webserver

### ISSUE THREAD

**Issue by tbrowder** [melezhik/Cromtit#1]
The desired command, as root:

    # apachectl graceful

The time should be at 0800 UTC every Sunday

Thanks.

**Comment by melezhik** [comment]
Hi @tbrowder , please take a look at this - https://github.com/melezhik/Cromtit/blob/main/cookbooks.md#restart-apache-server , please pay attention that timezone is resolved by local server time ( where Sparky server is installed )

**Comment by melezhik** [comment]
Sorry, this is correct link - https://github.com/melezhik/Cromtit/blob/main/cookbook.md#restart-apache-server

**Comment by melezhik** [comment]
Also - https://github.com/melezhik/cromtit-cookbook
